Bug/UI updates
glific/mobile pull request #133
Opened 2023-07-19 11:05 UTC by ajaman190

**Description:**
This PR address the issue #105.

**Changes Made:**
- Implemented block contact in the chat screen.
-  Updated the axios service configuration.
- Added tests for chat screen popups and wallets.
- Dropped unused variables.

**Screenshots:**

--
**Closes Issue:**

Closes #105

2023-07-19 13:13 UTC, mdshamoon requested changes

2023-07-19 13:13 UTC, mdshamoon commented on components/messages/ChatPopup.tsx
> +      ...(task === 'block' ? { input: { status: 'BLOCKED' } } : {}),
variables as well

2023-07-20 11:43 UTC, ajaman190 commented on components/headers/NotificationHeader.tsx
> +  // eslint-disable-next-line no-unused-vars
This is for preventing the lint error that is coming from the below line.

2023-07-21 10:00 UTC, mdshamoon approved these changes

2023-07-21 10:00 UTC, merged