Setup Jest and Add test cases for Login and Server screen
glific/mobile pull request #14
Opened 2023-05-16 06:48 UTC by ajaman190

### Description:
This pull request adds unit test cases for the Login component, addressing the issue mentioned in #11 . The tests cover various scenarios such as rendering, updating input values, handling empty inputs, and navigation to other screens.

### Changes Made:
- Installed and setup Jest
- Added yarn test command to run all test cases.
- Wrote test cases for the Login and Sever screen.

### Test Cases:
1. Sever Screen Test Cases:
- Render Test: Ensures that the Server component renders without any errors.
- Update Input Test: Verifies that the server URL input value is correctly updated when user input is entered.
- Empty Input Test: Tests the behavior when the server URL input is empty. Expects an error message to be displayed.
- Login Screen Navigation Test: Checks the navigation to the Login screen upon successful submission.

2. Login Screen Test Cases:
- Render Test: Ensures that the Login component renders without any errors.
- Update Input Test: Verifies that the input values are correctly updated when user input is entered.
- Empty Mobile Number Test: Tests the behavior when the mobile number input is empty. Expects an error message to be displayed.
- Empty Password Test: Tests the behavior when the password input is empty. Expects an error message to be displayed.
- Chat Screen Navigation Test: Checks the navigation to the Chat screen upon successful submission. **(Note: This I have commented because here before navigating to next(Chat) screen an API call is required.)**

### Coverage:
The test cases have been written to provide coverage for the important functionalities and user interactions. After running the tests, the coverage report will be generated, showcasing the code coverage achieved by the tests.

### Screenshots:
![image](https://github.com/glific/mobile/assets/84832565/295fc76c-c9cd-4449-ae36-eaf75729dde3)
![image](https://github.com/glific/mobile/assets/84832565/5a2982a9-0edd-48b7-916e-6e130dd1f106)
![image](https://github.com/glific/mobile/assets/84832565/ac32ab19-0903-431c-9b27-9e717d69f0b8)

Please review the pull request and provide any feedback or suggestions.

2023-05-16 06:58 UTC, ajaman190 commented
@mdshamoon Please review this pull request and ignore the 20 files in the coverage folder, as they are auto-generated by Jest for the coverage report.

2023-05-16 07:03 UTC, mdshamoon requested changes
Can you add the coverage folder into gitignore. So these files will not be committed

2023-05-16 08:32 UTC, ajaman190 commented
> Can you add the coverage folder into gitignore. So these files will not be committed

Sure

2023-05-16 11:41 UTC, mdshamoon commented on __tests__/Login.test.tsx
> +  // test("displays error message when password empty", async () => {
Why are these test cases commented out?

2023-05-16 11:46 UTC, mdshamoon commented on package.json
> +    ]
If possible can we create a separate setup file for jest and add these in the file. https://jestjs.io/docs/configuration

2023-05-16 11:46 UTC, mdshamoon reviewed
Overall looking good. Just check the above comments

2023-05-16 12:45 UTC, ajaman190 commented on __tests__/Login.test.tsx
> +  // test("displays error message when password empty", async () => {
I have mentioned the reason in the PR.

>Chat Screen Navigation Test: Checks the navigation to the Chat screen upon successful submission. (Note: I have commented this because here before navigating to next(Chat) screen a synchronous API call is required.)

See the below snap, this i got from the coverage, which indicates these three lines of code is not covered in the test.

![image](https://github.com/glific/mobile/assets/84832565/3f88a61c-7680-49ea-a057-9424cb800996)

2023-05-17 06:07 UTC, mdshamoon approved these changes

2023-05-17 06:07 UTC, merged