Adds subscription for contacts on chat page
glific/mobile pull request #150
Opened 2023-07-31 17:00 UTC by VishalZ123

## Adds subscriptions for contacts message on chat page

### Summary
This adds the feature of updating the contact card on the chat screen when a user sends or receives messages.

### Changes made
- Adds contact field in `MESSAGE_RECEIVED_SUBSCRIPTION` & `MESSAGE_RECEIVED_SUBSCRIPTION` subscriptions.
- Adds function to update the cache when a message is sent or received.

### Issues
Implements #139 

Please Review and merge

2023-08-02 06:48 UTC, mdshamoon requested changes

2023-08-02 06:48 UTC, mdshamoon commented on screens/Chat.tsx
> +/* eslint-disable prettier/prettier */
Why are we disabling this?

2023-08-02 06:48 UTC, mdshamoon commented on screens/Chat.tsx
> +      body = subscriptionData.data.receivedMessage.body;
I think this is similar to what we have done in message list. Can you create a common functiona and use in both places.

2023-08-03 21:54 UTC, VishalZ123 commented on screens/Chat.tsx
> +/* eslint-disable prettier/prettier */
It was added by mistake, removed it

2023-08-03 21:54 UTC, VishalZ123 commented on screens/Chat.tsx
> +      body = subscriptionData.data.receivedMessage.body;
Implemented

2023-08-07 05:33 UTC, ajaman190 commented
@VishalZ123 can you please fix all deep scan problems first.

2023-08-08 07:14 UTC, mdshamoon approved these changes

2023-08-08 07:14 UTC, merged