Dynamic Contact Information and History
glific/mobile pull request #153
Opened 2023-08-05 05:21 UTC by VishalZ123

## Dynamic Contact Info and History

**Summary**
Implements the dynamic contact info and history. Uses `GET_CONTACT_INFO` for fetching the contact information, formats it and displays. More info option displays the fields for the contact. Contact History option displays all the action taken for the contact, using the `GET_CONTACT_HISTORY` query.

**Changes Made**
- Implements dynamic contact information
- Adds More info page that displays the fields for the contacts
- Adds the Contact History page that displays the history actions of a contact
- Load more history on scroll
- Adds tests and mocks for unit testing

https://github.com/glific/mobile/assets/76409986/4f44ae6f-2b8c-4de4-b372-50a3e298ec22

**Issues**
Implements #140 

**Reviewers**
@mdshamoon , Kindly review and merge

2023-08-06 04:02 UTC, ajaman190 commented
Hey @VishalZ123, please resolve all the deep scan issues.

2023-08-07 06:16 UTC, ajaman190 requested changes

2023-08-07 06:28 UTC, VishalZ123 commented on screens/ContactInfo.tsx
> +        ) : (
If there are no fields then the fields are empty, like not even title are present.
These are created as key value pairs while creating the flows.

2023-08-08 11:21 UTC, VishalZ123 commented on __tests__/ContactProfile.test.tsx
> +    };
okay, I must have overlooked the use of `navigationMock` in multiple places in the same fiel

2023-08-08 11:32 UTC, VishalZ123 commented on __tests__/ContactHistory.test.tsx
> +    fireEvent(flatList, 'onEndReached');
I don't get it, the line which you changed was not using the `eventData`, can you clarify
also, can you please specify the test in chat screen which you are talking about. The file name and line. there's no test as "renders correctly" in `ChatScreen.test.tsx`

2023-08-09 06:16 UTC, mdshamoon approved these changes

2023-08-09 06:16 UTC, merged