Add Collection to Contact and Contacts to Collection
glific/mobile pull request #169
Opened 2023-08-17 10:54 UTC by VishalZ123

## Collection to Contact and Contact to Collection addition feature

## Description
The PR implements the `Add collection to contact` feature on the contact chat screen and `Add contacts to collection` feature on the collection chat screen.
Depending on the chat screen type (contact or collection) we fetch all options for contacts or collections respectively via `GET_CONTACTS` & `GET_COLLECTIONS_LIST` queries.
We also fetch the collections in which the current contact is added or contacts added in the current collection respectively via `GET_CONTACT_COLLECTIONS` & `GET_COLLECTION_CONTACTS` queries. We use MultiSelect for selecting the options and selected and deleted options are used to make a mutation `ADD_COLLECTIONS_TO_CONTACT` or `ADD_CONTACTS_TO_COLLECTION` to add/delete options.
The MultiSelect component was changed to remove the close button.

## Changes Made

- [x] Change 1: Adds a Collection Popup to add Collections to Contact or Contacts to Collections
- [x] Change 2: Adds queries to get list of all collections, all contacts, contacts of a collection and collection of a contact.
- [x] Change 3: Adds mutation to add collections to contact and contact to collection.
- [x] Change 4: Change MultiSelect component to optionally remove the close option from the options.
- [ ] Change 5: Remove option to delete contacts from Add contacts to Collection options.
- [ ] Change 6: Pass Tests.

## Screenshots

https://github.com/glific/mobile/assets/76409986/72de9ece-bd1f-4172-b43d-3907af4fbbdd

## Related Issues

Closes: #156 & #157 

## Reviewer
@mdshamoon & @ajaman190 Please Review

---

2023-08-17 11:51 UTC, ajaman190 commented
@VishalZ123 Please fix all possible deep scan problems first.

2023-08-17 12:12 UTC, ajaman190 requested changes

2023-08-17 12:12 UTC, ajaman190 commented on components/messages/CollectionPopup.tsx
> +  };
Define this function outside the component,
```sh
const formatOptions = (data: object, isContactType: boolean) => {
  return data.map((element: any) => {
    const id = isContactType ? element.id : element.contact.id;
    const name = isContactType ? element.label : element.contact.name || element.contact.maskedPhone;
    const label = isContactType ? 'Collections' : 'Contacts';
    
    return {
      id,
      name,
      label,
    };
  });
};
```

And also try to add proper type instead of any.
```sh
const formatAllOptions = (data: any, isContactType: boolean) => {
  const options = formatOptions(data.groups, isContactType);
  setAllOptions(options);
};

const formatSelectedOptions = (data: any, isContactType: boolean) => {
  const options = formatOptions(isContactType ? data.contact.contact.groups : data.group.group.contacts, isContactType);
  setSelectedOptions(options);
};
```

2023-08-18 07:31 UTC, VishalZ123 commented on components/messages/CollectionPopup.tsx
> +  };
The data is not so straightforward, so your exact suggestions won't work but I have done something similar to this.
Remaining tasks - 
- [ ] Tests
- [ ] Deep Scan Issues

2023-08-21 04:42 UTC, mdshamoon requested changes

2023-08-21 04:42 UTC, mdshamoon commented on components/headers/ChatHeader.tsx
> +    : {
```suggestion
  const optionVariables = isContactType
    ? {
        filter: {},
        opts: { limit: 50, offset: 0, order: 'ASC' },
      }
    : {
```

have a limit of 50 for now. Contacts could go up to 1 lakh. We need to make this dynamic and searchable. 
Let's put a limit for now and add the search and select functionality in a new PR

2023-08-21 08:24 UTC, VishalZ123 commented on components/headers/ChatHeader.tsx
> +    : {
Sure, made suggested changes.

2023-08-23 15:45 UTC, mdshamoon approved these changes

2023-08-23 15:46 UTC, mdshamoon approved these changes

2023-08-23 15:46 UTC, merged