Adds Collection Info
glific/mobile pull request #175
Opened 2023-08-24 21:40 UTC by VishalZ123

## Description
The PR implements the feature of Viewing Collection info. Used queries- `COUNT_COLLECTION_CONTACTS` & `GET_COLLECTION_INFO` to get number of contacts in a collection and collection info respectively. Also created `CollectionProfile` and `CollectionContacts` screens.

## Changes Made

- [x] Change 1: Added navigation for collection profile page.
- [x] Change 2: Added a Collection profile page to show collection description and info.
- [x] Change 3: Added a Collection Contacts page to view the list of all contacts of a collection.
- [ ] Change 4: Fetch details such as Session Messages, Only Templates & No Messages dynamically

## Screenshots

https://github.com/glific/mobile/assets/76409986/009d5b7a-7a7e-4340-8325-56da18863710

## Related Issues

Closes: #173 

## Reviewers
@mdshamoon , Please review the PR and merge after all the tasks are complete.

---

2023-08-29 14:50 UTC, mdshamoon requested changes

2023-08-29 14:50 UTC, mdshamoon commented on screens/CollectionContacts.tsx
> +    },
```suggestion

  const { data, loading } = useQuery(GET_COLLECTION_CONTACTS, {
    variables: { id: collectionId },
    nextFetchPolicy: 'network-only',
```

Use data value directly rather than adding to a state.

2023-08-29 14:50 UTC, mdshamoon commented on screens/CollectionProfile.tsx
> +              {/*TODO: Use Api to fetch */}
Is it still Todo?

2023-08-29 15:24 UTC, VishalZ123 commented on screens/CollectionProfile.tsx
> +              {/*TODO: Use Api to fetch */}
No, I forgot to remove the comment.

2023-09-03 06:10 UTC, mdshamoon approved these changes

2023-09-03 06:10 UTC, merged