Add wallet balance option in the sidedrawer #41
glific/mobile pull request #44
Opened 2023-05-23 18:30 UTC by chandra-pro

Added the wallet component in sidebar.As of now Apollo is showing error of network request failed so i comment out that code.

2023-05-24 05:16 UTC, mdshamoon commented on components/messages/Message.tsx
> +    } else if (!isLeft && type === 'message') {
Please update this function with a switch case:

const isOnLeft = (type: any) => {
  switch (type) {
    case 'time':
    case 'message':
      return isLeft ? { color: 'white' } : { color: 'black' };

    case 'messageContainer':
      return isLeft
        ? {
            alignSelf: 'flex-start',
            backgroundColor: '#073F24',
            borderTopLeftRadius: 0,
          }
        : {
            borderTopRightRadius: 0,
            color: '#E1E8E5',
          };

    default:
      return {
        borderTopRightRadius: 0,
        color: '#E1E8E5',
      };
  }
};

2023-05-24 05:19 UTC, mdshamoon requested changes
Let me know what is the issue you are getting while calling the walletBallance API

2023-05-24 05:51 UTC, chandra-pro commented
> Let me know what is the issue you are getting while calling the walletBallance API

I was getting error of network request failed.

2023-05-24 05:54 UTC, mdshamoon commented
@chandra-pro it can only be called under the apollo client provider. make sure your component is a child of the apollo client provider

2023-05-24 09:38 UTC, chandra-pro commented
@mdshamoon I have done what you have told but data is not rendered. Please look into the code

2023-05-24 12:01 UTC, mdshamoon commented
@chandra-pro I meant the ApolloProvider we already defined in Chat.tsx file

The way it works is when you make a call with useQuery it checks if it needs to add any header or other configurations from the ApolloProvider anywhere in the parent chain. We have added auth header in the ApolloProvider used in Chat.tsx

The way you can do is to move ApolloProvider out of Chat.tsx and add in App.tsx 
With this Wallet component will be a child of ApolloProvider and the call will be made with the authentication header.

Let me know if this makes sense. Or we can also have a call and I can explain

2023-05-24 12:48 UTC, chandra-pro commented
I have already use Apollo provider in app.tsx to make the component as a
child of this.
Please see the code once.

On Wed, May 24, 2023, 5:31 PM Mohd Shamoon ***@***.***> wrote:

> @chandra-pro <https://github.com/chandra-pro> I meant the ApolloProvider
> we already defined in Chat.tsx file
>
> The way it works is when you make a call with useQuery it checks if it
> needs to add any header or other configurations from the ApolloProvider
> anywhere in the parent chain. We have added auth header in the
> ApolloProvider used in Chat.tsx
>
> The way you can do is to move ApolloProvider out of Chat.tsx and add in
> App.tsx
> With this Wallet component will be a child of ApolloProvider and the call
> will be made with the authentication header.
>
> Let me know if this makes sense. Or we can also have a call and I can
> explain
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/glific/mobile/pull/44#issuecomment-1560989866>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ASBL25MESXVZVETODIPU2LDXHX2APANCNFSM6AAAAAAYMI6FGM>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-05-24 12:54 UTC, mdshamoon commented
You have created a separate client and not used the one already present which is configured for adding header.

<img width="436" alt="image" src="https://github.com/glific/mobile/assets/32592458/1a69383e-2c44-43b4-b00e-96d240a0a352">

Please see if that works and remove from the provider from Chat.tsx once you add here.

2023-05-24 13:07 UTC, mdshamoon commented on components/ui/Wallet.tsx
> +        <View>
@chandra-pro I have checked the code by pulling on local and I can see that you are getting the data as an object. 

add a console here and you will see that you are getting the data in this format {"bspbalance": "{\"balance\":4.874}"} which is an object.

You have to extract the string from here and then display it

2023-05-24 20:38 UTC, mdshamoon commented
@chandra-pro want to have a quick call if available to check the issue

2023-05-24 21:18 UTC, chandra-pro commented
yeah available

2023-05-24 21:19 UTC, mdshamoon commented
@chandra-pro are you on discord? If yes can you share your name or id I can send the link there

2023-05-24 21:22 UTC, chandra-pro commented
aldehyde#1074

2023-05-25 11:22 UTC, chandra-pro commented
@mdshamoon still getting Apollo Error and the value of data as undefined.
Could you please help me regarding this.

2023-05-26 08:08 UTC, mdshamoon commented
@chandra-pro let me take over this since it is working fine for me. Can you complete #52 meanwhile

2023-05-27 06:02 UTC, mdshamoon commented
Closing in favor of #65

2023-05-27 06:02 UTC, closed without merging