Fixes: Open the contact messages page with contact details
glific/mobile pull request #53
Opened 2023-05-25 02:25 UTC by ajaman190

### Description
This pull request addresses the issue #48

### Changes Made
1. Recreated the header and menu implementation to enhance the user interface and improve usability.
2. Implemented a GraphQL query to fetch user data, specifically the contact details. Currently, the query only retrieves the user's contact details. However, even if there are no messages available, an empty array for the messages is included in the response. Please review the query:
 `{filter: {id: "21"}, contactOpts: {limit: 1}, messageOpts: {limit: 20, offset: 1}}`

**Response getting:**

![image](https://github.com/glific/mobile/assets/84832565/2ffa95a0-49fb-4f13-84f0-ba4a09068f5d)

### Screenshots
https://github.com/glific/mobile/assets/84832565/cba4f7e7-1308-4e96-8942-723a61cbae2e

### Closes Issue
Closes #48

2023-05-25 05:14 UTC, mdshamoon commented on screens/ChatScreen.tsx
> +    filter: { id: '21' },
```suggestion
    filter: { id: contactId },
```
contactId will be passed as a prop to this component. You will get the contact id by modifying the search query as follows

```
search(filter: $filter, contactOpts: $contactOpts, messageOpts: $messageOpts) {
      contact {
        id
        name
        maskedPhone
      }
    }
```

2023-05-25 05:17 UTC, mdshamoon reviewed
For getting messages update the search query in this format

search(filter: $filter, contactOpts: $contactOpts, messageOpts: $messageOpts) {
      contact {
        name
        maskedPhone
      }
     messages {
        id
        body
        insertedAt
        }
    }

2023-05-25 05:20 UTC, mdshamoon commented
@ajaman190 can I know your discord Id? Will be easier to communicate there.

2023-05-25 10:03 UTC, mdshamoon commented
@ajaman190 please check the test cases. Also replace ApolloProvider in test with MockedProvider
https://www.apollographql.com/docs/react/development-testing/testing/

2023-05-25 10:15 UTC, mdshamoon commented
@ajaman190 also align the messages left or right based on this logic

```
const isSender = message.sender.id === contact.id
if(isSender){
align left
}
else{
align right
}
```

The data for sender will be under messages 

```
  search(filter: $filter, contactOpts: $contactOpts, messageOpts: $messageOpts) {
      contact {
        id
        name
        phone
      }
      messages {
        id
        body
        sender {
          id
        }
      }
    }
  

```

2023-05-25 10:42 UTC, mdshamoon reviewed
Please check the comment for aligning messages. Also decrease font size of time left

2023-05-25 17:56 UTC, mdshamoon requested changes

2023-05-25 17:56 UTC, mdshamoon commented on components/messages/ChatHeader.tsx
> +  userData: {
```suggestion
  contact: {
```

2023-05-25 17:56 UTC, mdshamoon commented on components/messages/ChatHeader.tsx
> +const ChatHeader: React.FC<DataProps> = ({ userData }) => {
```suggestion
const ChatHeader: React.FC<DataProps> = ({ contact }) => {
```

2023-05-25 17:56 UTC, mdshamoon commented on components/messages/ChatHeader.tsx
> +              <Ionicons name="person-add-sharp" style={styles.menuIcon} />
Instead of using all these pressables. See if we can use a library and creaate a menu component that can be reused

2023-05-25 17:56 UTC, mdshamoon commented on components/messages/Message.tsx
> +    // backgroundColor: COLORS.primary100,
Remove comment if not needed

2023-05-25 17:56 UTC, mdshamoon commented on components/messages/MessageList.tsx
> +  }, [error, data]);
Prefer to avoid using useEffect unless absolutely necessary, since this is difficult to understand when someone reads the code and try to check the flow of execution.

```suggestion
  let messages= []
  if(loading) return <Loading />
   if (error) {
      console.log(error);
    } 
     if (data) {
     messages = data.search[0].messages;
    }
```

2023-05-25 17:56 UTC, mdshamoon commented on screens/ChatScreen.tsx
> +  // const [isLeft, setIsLeft] = useState(false);
Remove if not needed

2023-05-25 17:56 UTC, mdshamoon commented on components/messages/MessageList.tsx
> +              isLeft={message?.sender?.id != userData.id}
```suggestion
              isLeft={message?.sender?.id == userData.id}
```

2023-05-26 03:36 UTC, ajaman190 commented
https://github.com/glific/mobile/assets/84832565/0276ba41-9323-40c1-965c-b202bfb4fbd0

2023-05-26 03:41 UTC, ajaman190 commented on components/messages/MessageList.tsx
> +              isLeft={message?.sender?.id != userData.id}
why? if the sender id is not equals to the user id, then message is not associated with user so it need to be on left side.

2023-05-26 03:44 UTC, ajaman190 commented on components/messages/ChatHeader.tsx
> +              <Ionicons name="person-add-sharp" style={styles.menuIcon} />
Created a button component and reused it.

2023-05-26 04:33 UTC, mdshamoon commented on components/messages/MessageList.tsx
> +              isLeft={message?.sender?.id != userData.id}
We want to keep all the messaeges that have been sent by the contact on the left and the message that we sent from the bot on the left. When a contact sends a message to the bot the sender id becomes the contact id.

2023-05-26 04:33 UTC, mdshamoon commented on __tests__/Collections.test.tsx
> +  const mockGroups = [
We can do this later but lets move all the mocks to a different folder

2023-05-26 04:35 UTC, mdshamoon approved these changes
Great work. Looks really good 👍

2023-05-26 04:35 UTC, merged