Created tabs for Notifications Page
glific/mobile pull request #57
Opened 2023-05-26 07:35 UTC by SoumyadiptoPal

solved Issue #55
Created the notifications page.
Used a hard-coded object array for development purpose. Each object contains a header, message, time and type.  Also added 3 images for critical, warning and info types of messages.
![screen (1)](https://github.com/glific/mobile/assets/119007659/cd4c9c7d-368d-4bcd-94e3-7e90483a506e)

2023-05-26 10:14 UTC, mdshamoon requested changes
Please format the code with prettier. and use svg instead of png for images

2023-05-26 10:14 UTC, mdshamoon commented on screens/Notifications.tsx
> +  }
```suggestion
const handleOptionPress = (option) => {
setOption(option);
if (option === "All") {
setNotificationArray(Notifications);
} else {
const filteredArray = filterArrayByField(option);
setNotificationArray(filteredArray);
}
};
```

2023-05-26 10:14 UTC, mdshamoon commented on screens/Notifications.tsx
> +      <ScrollView>
```suggestion
    const RenderOptionButton = ({ label, selectedOption, onPress }) => {
  const isActive = selectedOption === label;
  return (
    <View style={isActive ? styles.option : {}}>
      <TouchableOpacity onPress={onPress}>
        <Text style={[styles.text, isActive ? styles.active : {}]}>
          {label}
        </Text>
      </TouchableOpacity>
    </View>
  );
};

// Usage:
<View style={styles.navBar}>
  <RenderOptionButton label="All" selectedOption={option} onPress={pressedAll} />
  <RenderOptionButton label="Critical" selectedOption={option} onPress={pressedCritical} />
  <RenderOptionButton label="Warning" selectedOption={option} onPress={pressedWarning} />
  <RenderOptionButton label="Info" selectedOption={option} onPress={pressedInfo} />
</View>
```

2023-05-26 10:25 UTC, ajaman190 commented
> Please format the code with prettier. and use svg instead of png for images

Unfortunately, we cannot use SVG directly in a React Native project. However, I have come across two better solutions:
1. Use the `react-native-svg-transformer` package to render SVG code.
2. If the icon is of a single color, convert the icons into a font family and use it as a normal font. This approach also helps reduce the overall app size.

2023-05-27 05:14 UTC, mdshamoon commented
Closing in favor of #62

2023-05-27 05:14 UTC, closed without merging