updated contactlist ui #56
glific/mobile pull request #74
Opened 2023-05-28 14:17 UTC by chandra-pro

I have attached the screenshot.Please review it and let me know if there require any changes.
![WhatsApp Image 2023-05-28 at 7 46 07 PM](https://github.com/glific/mobile/assets/75677045/15264558-4a67-473c-813e-d3d59afe4130)

2023-05-28 14:58 UTC, mdshamoon requested changes

2023-05-28 14:58 UTC, mdshamoon commented on components/ui/CollectionList.tsx
Rename to CollectionListItem

2023-05-28 14:58 UTC, mdshamoon commented on components/ui/CollectionList.tsx
> +  console.log();
Remove console

2023-05-28 14:58 UTC, mdshamoon commented on components/ui/CollectionMain.tsx
> +  lastMessageAt: string;
We don't need this in Collection

2023-05-28 14:58 UTC, mdshamoon commented on components/ui/CollectionMain.tsx
> +  },
```suggestion
  name: {
    fontSize: SIZES.f16,
    marginLeft: SIZES.m18,
  },
```

Use SIZES for all styles

2023-05-28 14:58 UTC, mdshamoon commented on components/ui/Contact.tsx
> +  ];
```suggestion
  lastMessage: string
```

Just pass the last message rather than all messages

2023-05-28 14:58 UTC, mdshamoon commented on components/ui/Contact.tsx
> +  const getSessionTimeLeft = (time: string) => {
Use this function from ChatScreen.tsx

2023-05-28 14:58 UTC, mdshamoon commented on screens/ChatScreen.tsx
> +console.log();
remove console

2023-05-28 14:58 UTC, mdshamoon commented on screens/ChatScreen.tsx
> +  console.log(route);
Remove console

2023-05-28 15:18 UTC, chandra-pro commented on screens/ChatScreen.tsx
> +console.log();
I got an error of params undefined

2023-05-28 15:39 UTC, chandra-pro commented on components/ui/Contact.tsx
> +  ];
On removing I got deep Scan issues.

2023-05-28 15:40 UTC, chandra-pro commented on components/ui/Contact.tsx
> +  const getSessionTimeLeft = (time: string) => {
I got an error of undefined params error.

2023-05-28 18:12 UTC, mdshamoon requested changes

2023-05-28 18:12 UTC, mdshamoon commented on components/ui/Contact.tsx
> +  const getSessionTimeLeft = (time: string) => {
I don't understand. You need add to export the function from that file there import it here. How do you get an undefined param?

2023-05-28 18:12 UTC, mdshamoon commented on screens/ChatScreen.tsx
> +  console.log(route);
This is still not removed

2023-05-28 18:12 UTC, mdshamoon commented on components/ui/Contact.tsx
> +  ];
I don't understand how changing props defination is related to deepscan issue. Please check what the deepscan issue is saying and resolve appropriately.

2023-05-29 03:55 UTC, mdshamoon reviewed
Overall looks good. Added some comments please check

2023-05-29 03:55 UTC, mdshamoon commented on components/ui/Contact.tsx
>    }
We don't need this. If the last message is not present there will be empty space below the contact name

2023-05-29 03:55 UTC, mdshamoon commented on components/ui/ContactList.tsx
> +      const Messages = element.messages;
const messages = element.messages; 

Variable names will be camelCase

2023-05-29 03:55 UTC, mdshamoon commented on components/ui/ContactList.tsx
> +        lastMessage: Messages[Messages.length - 1]?.body,
lastMessage: messages.length > 0 && messages[messages.length - 1]?.body,

Check if messages are not empty.

2023-05-29 07:39 UTC, mdshamoon approved these changes

2023-05-29 07:39 UTC, merged