SOLVE issue-Add an emoji library to add emojis in a message that we c…
glific/mobile pull request #84
Opened 2023-06-14 11:01 UTC by nishant25062002

…an send #56

2023-06-15 10:58 UTC, mdshamoon requested changes
When I am selecting the emoji for the first time in a chat. It adds undefined in the text.

2023-06-15 10:58 UTC, mdshamoon commented on package-lock.json
We are using yarn for development. Please remove this file.

2023-06-15 10:58 UTC, mdshamoon commented on package.json
> -    "react-native-tab-view": "^3.5.1"
Why did we remove this?

2023-06-16 05:33 UTC, nishant25062002 commented on package.json
> -    "react-native-tab-view": "^3.5.1"
Sorry I removed due to some confusion.

2023-06-16 05:34 UTC, nishant25062002 commented on package-lock.json
I have removed.

2023-06-16 14:43 UTC, ajaman190 requested changes

2023-06-16 14:43 UTC, ajaman190 commented on components/messages/ChatInput.tsx
> +        {showEmoji && (
https://github.com/glific/mobile/assets/84832565/aea2522d-e347-4ffe-8316-48b84aa053aa

1. As you can see, currently, multiple states are active at the same time. Can you create a single tab in which the content changes according to the state (emojis, attachments, options), similar behavior you can observe in WhatsApp.
2. When the emoji tab is open, replace the emoji button with a keyboard button. which on press the switch to the device keyboard and close the emoji tab.

2023-06-16 15:43 UTC, Abro0058T commented on components/messages/ChatInput.tsx
> +        {showEmoji && (
@nishant25062002  ig you can make the update faster by making the whole input part as a separate component . When ever we type or in this case select an emoji the whole ChatInput component is rendering again and ig this is why the emoji update is slow . Besides u have used  8-10 libraries for this issue but none of them quick enough , the one which is quick is making a significant change in UX .

2023-06-20 14:08 UTC, mdshamoon approved these changes
Please resolve merge conflicts and merge after that.

2023-06-20 14:54 UTC, closed without merging